# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1502e2ac5f5f7cf2c93412de6ddaa45fcc3095d338461fe10a8653a263734c6916dfcecfb65bcf087dbacfe3652650ffeba06c244973730d570a6a1cb7fe3e33

test:
  secret_key_base: 44654b55529c7b332cf8809b78991c55cc06b1e58ccb78f4e26de2c81aef86c5a3daa033dbff52b6e92f5529c2b54687bbbac8bc831bf204d10f19a6eac67436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
